version: "3"

services:
  wazi-app:
    image: waziup/wazigate-jupyterlab:64
    container_name: waziup.wazigate-jupyterlab
    build:
      context: ./
    volumes:
      - /var/lib/wazigate/apps/waziup.wazigate-jupyterlab:/var/lib/waziapp/
    ports:
      - "9000:9000"
    privileged: true
    restart: unless-stopped
    environment:
      - TEST_VAR=1
    healthcheck:
      test: curl --fail --unix-socket /var/lib/wazigate/apps/waziup.wazigate-jupyterlab/proxy.sock http://localhost/ || exit 1 #curl --fail http://localhost:5000/ || exit 1
      interval: 30s
      retries: 10 # Will try for 5 minutes